[package]
name = "randomx-sys"
version = "0.1.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
edition = "2018"

[dependencies]
link-cplusplus = "1.0.4"

[build-dependencies]
bindgen = "0.56.0"
cmake = "0.1.45"
